---
- name: Install Cargo, clone a GitHub Rust project, and compile it
  hosts: '{{ target }}'
  become: yes
  vars:
    begin: 0
    bash: 8
    end: 50
  tasks:
    - name: Get current working directory
      command: pwd
      register: current_directory
    - name: Ansible check file exists.
      stat:
        path: /root/Aupe/s9.sh
      register: p
    - debug:
        msg: "File exists..."
      when: p.stat.exists
    - name: Execute the script
      ansible.builtin.debug:
        msg: "test {{ begin }} {{ bash }} {{ end }}"
    - name: Execute the script
      command: sh /root/Aupe/s9.sh {{ bash |int }} {{ begin |int }}  {{ end |int }}
      register: receivers
    - debug:
       var: receivers.stdout
    