---
- name: Install Cargo, clone a GitHub Rust project, and compile it
  hosts: '{{ target }}'
  become: yes
  tasks:
    - name: Get current working directory
      command: pwd
      register: current_directory
    - name: Ansible check file exists.
      stat:
        path: /root/Aupe/expe.sh
      register: p
    - debug:
        msg: "File exists..."
      when: p.stat.exists
    - name: Install a snap package
      ansible.builtin.command:
        cmd: pkill basalt
    - name: Execute the script
      command: sh /root/Aupe/expe.sh 0 1 3
      register: receivers
    - debug:
       var: receivers.stdout
    