---
- name: Install Cargo, clone a GitHub Rust project, and compile it
  hosts: '{{ target }}'
  become: yes
  tasks:
    - name: Get current working directory
      command: pwd
      register: current_directory
    - name: Ansible check file exists.
      stat:
        path: /root/Aupe/expe/expe.sh
      register: p
    - debug:
        msg: "File exists..."
      when: p.stat.exists
    - name: Execute the script
      command: sh /root/Aupe/expe.sh
      register: receivers
    - debug:
       var: receivers.stdout
    