---
- name: Install Cargo, clone a GitHub Rust project, and compile it
  hosts: '{{ target }}'
  become: yes
  vars:
    begin: 0
    rep: 3
    end: 50
  tasks:
    - name: Get current working directory
      command: pwd
      register: current_directory
    - name: Ansible check file exists.
      stat:
        path: /root/Aupe/expe.sh
      register: p
    - debug:
        msg: "File exists..."
      when: p.stat.exists
    - name: Execute the script
      ansible.builtin.debug:
        msg: "test {{ begin }} {{ rep }} {{ end }}"
    - name: Execute the script
      command: sh /root/Aupe/expe.sh {{ begin |int }} {{ rep |int }} {{ end |int }}
      register: receivers
    - debug:
       var: receivers.stdout
    