- hosts: '{{ target }}'
  gather_facts: true
  become: true
  become_user: root

  vars:
    user: "{{ ansible_user_id }}"
  tasks:
  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust
  - name: Install a snap package
    ansible.builtin.command:
      cmd: sudo apt update
  - name: Install a snap package
    ansible.builtin.command:
      cmd: snap install rustup --classic
  - name: Install a snap package
    ansible.builtin.command:
      cmd: rustup default stable
  - name: Install build-essential
    action: apt pkg=build-essential
  - name: Clone the GitHub repository
    git:
      repo: 'https://github.com/labri-progress/Aupe.git'
      dest: ~/Aupe
      version: main
  
