[package]
name = "aupe"
version = "0.1.0"
edition = "2018"
authors = ["Augusta MUKAM <augusta.mukam@u-bordeaux.fr>"]

[dependencies]
rand = "0.5.5"
itertools = "0.7.5"
rayon = "1.3.0"
fasthash = "0.4.0"
structopt = "0.3.3"
once_cell = "1.10.0"
lazy_static = "1.4.0"
